-- MySQL Script generated by MySQL Workbench
-- Thu Apr 21 04:39:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema REDO_MAKMA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema REDO_MAKMA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `REDO_MAKMA` DEFAULT CHARACTER SET utf8 ;
USE `REDO_MAKMA` ;

-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`FrecuenciaVisita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`FrecuenciaVisita` (
  `idFrecuenciaVisita` INT NOT NULL AUTO_INCREMENT,
  `frecuencia` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idFrecuenciaVisita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`GrupoDia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`GrupoDia` (
  `idGrupoDia` INT NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idGrupoDia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Beneficiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Beneficiario` (
  `idBeneficiario` INT NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `credencial` MEDIUMBLOB NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 1,
  `beca` TINYINT(2) NULL DEFAULT 0,
  `fRegistro` DATE NOT NULL,
  `fVencimiento` DATE NOT NULL,
  `frecuenciaVisita_idFrecuenciaVisita` INT NULL,
  `grupoDia_idGrupoDia` INT NULL,
  `sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idBeneficiario`),
  INDEX `fk_Beneficiario_FrecuenciaVisita1_idx` (`frecuenciaVisita_idFrecuenciaVisita` ASC),
  INDEX `fk_Beneficiario_GrupoDia1_idx` (`grupoDia_idGrupoDia` ASC),
  INDEX `fk_Beneficiario_Sucursal1_idx` (`sucursal_idSucursal` ASC),
  UNIQUE INDEX `folio_UNIQUE` (`folio` ASC),
  CONSTRAINT `fk_Beneficiario_FrecuenciaVisita1`
    FOREIGN KEY (`frecuenciaVisita_idFrecuenciaVisita`)
    REFERENCES `REDO_MAKMA`.`FrecuenciaVisita` (`idFrecuenciaVisita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Beneficiario_GrupoDia1`
    FOREIGN KEY (`grupoDia_idGrupoDia`)
    REFERENCES `REDO_MAKMA`.`GrupoDia` (`idGrupoDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Beneficiario_Sucursal1`
    FOREIGN KEY (`sucursal_idSucursal`)
    REFERENCES `REDO_MAKMA`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(140) NOT NULL,
  `password` VARCHAR(56) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `rol_idRol` INT NOT NULL,
  `sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol_idx` (`rol_idRol` ASC),
  INDEX `fk_Usuario_Sucursal1_idx` (`sucursal_idSucursal` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC),
  CONSTRAINT `fk_Usuario_Rol`
    FOREIGN KEY (`rol_idRol`)
    REFERENCES `REDO_MAKMA`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Sucursal1`
    FOREIGN KEY (`sucursal_idSucursal`)
    REFERENCES `REDO_MAKMA`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(50) NOT NULL,
  `estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX `fk_Municipio_Estado1_idx` (`estado_idEstado` ASC),
  CONSTRAINT `fk_Municipio_Estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `REDO_MAKMA`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Comunidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Comunidad` (
  `idComunidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `status` TINYINT(2) NOT NULL,
  `sucursal_idSucursal` INT NOT NULL,
  `municipio_idMunicipio` INT NOT NULL,
  PRIMARY KEY (`idComunidad`),
  INDEX `fk_Comunidad_Sucursal1_idx` (`sucursal_idSucursal` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_Comunidad_Municipio1_idx` (`municipio_idMunicipio` ASC),
  CONSTRAINT `fk_Comunidad_Sucursal1`
    FOREIGN KEY (`sucursal_idSucursal`)
    REFERENCES `REDO_MAKMA`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comunidad_Municipio1`
    FOREIGN KEY (`municipio_idMunicipio`)
    REFERENCES `REDO_MAKMA`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`MiembroComite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`MiembroComite` (
  `idMiembroComite` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idMiembroComite`),
  INDEX `fk_MiembroComite_Comunidad1_idx` (`comunidad_idComunidad` ASC),
  CONSTRAINT `fk_MiembroComite_Comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `REDO_MAKMA`.`Comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Peticion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Peticion` (
  `idPeticion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantPaquetesEnv` INT NOT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  `miembroComite_idMiembroComite` INT NOT NULL,
  PRIMARY KEY (`idPeticion`),
  INDEX `fk_Peticion_Comunidad1_idx` (`comunidad_idComunidad` ASC),
  INDEX `fk_Peticion_MiembroComite1_idx` (`miembroComite_idMiembroComite` ASC),
  CONSTRAINT `fk_Peticion_Comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `REDO_MAKMA`.`Comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peticion_MiembroComite1`
    FOREIGN KEY (`miembroComite_idMiembroComite`)
    REFERENCES `REDO_MAKMA`.`MiembroComite` (`idMiembroComite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`AsistenciaPunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`AsistenciaPunto` (
  `idAsistenciaPunto` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `beneficiario_idBeneficiario` INT NOT NULL,
  PRIMARY KEY (`idAsistenciaPunto`),
  INDEX `fk_AsistenciaPunto_Beneficiario1_idx` (`beneficiario_idBeneficiario` ASC),
  CONSTRAINT `fk_AsistenciaPunto_Beneficiario1`
    FOREIGN KEY (`beneficiario_idBeneficiario`)
    REFERENCES `REDO_MAKMA`.`Beneficiario` (`idBeneficiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`MotivoTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`MotivoTipo` (
  `idMotivoTipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMotivoTipo`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Motivo` (
  `idMotivo` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(50) NOT NULL,
  `MotivoTipo_idMotivoTipo` INT NOT NULL,
  PRIMARY KEY (`idMotivo`),
  UNIQUE INDEX `motivo_UNIQUE` (`motivo` ASC),
  INDEX `fk_Motivo_MotivoTipo1_idx` (`MotivoTipo_idMotivoTipo` ASC),
  CONSTRAINT `fk_Motivo_MotivoTipo1`
    FOREIGN KEY (`MotivoTipo_idMotivoTipo`)
    REFERENCES `REDO_MAKMA`.`MotivoTipo` (`idMotivoTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Justificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Justificacion` (
  `idJustificacion` INT NOT NULL AUTO_INCREMENT,
  `fechaPedido` DATE NOT NULL,
  `fechaJustificada` DATE NOT NULL,
  `beneficiario_idBeneficiario` INT NOT NULL,
  `motivo_idMotivo` INT NOT NULL,
  PRIMARY KEY (`idJustificacion`),
  INDEX `fk_Justificaciones_Beneficiario1_idx` (`beneficiario_idBeneficiario` ASC),
  INDEX `fk_Justificaciones_Motivo1_idx` (`motivo_idMotivo` ASC),
  CONSTRAINT `fk_Justificaciones_Beneficiario1`
    FOREIGN KEY (`beneficiario_idBeneficiario`)
    REFERENCES `REDO_MAKMA`.`Beneficiario` (`idBeneficiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Justificaciones_Motivo1`
    FOREIGN KEY (`motivo_idMotivo`)
    REFERENCES `REDO_MAKMA`.`Motivo` (`idMotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`ReporteMensual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`ReporteMensual` (
  `idReporteMensual` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFinal` DATE NULL,
  `listasAsistencia` MEDIUMBLOB NULL,
  `cantFirmas` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idReporteMensual`),
  INDEX `fk_AsistenciaComunidad_Comunidad1_idx` (`comunidad_idComunidad` ASC),
  CONSTRAINT `fk_AsistenciaComunidad_Comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `REDO_MAKMA`.`Comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`Falta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`Falta` (
  `idFalta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `status` TINYINT(2) NOT NULL,
  `beneficiario_idBeneficiario` INT NOT NULL,
  `motivo_idMotivo` INT NULL,
  PRIMARY KEY (`idFalta`),
  INDEX `fk_Falta_Beneficiario1_idx` (`beneficiario_idBeneficiario` ASC),
  INDEX `fk_Falta_Motivo1_idx` (`motivo_idMotivo` ASC),
  CONSTRAINT `fk_Falta_Beneficiario1`
    FOREIGN KEY (`beneficiario_idBeneficiario`)
    REFERENCES `REDO_MAKMA`.`Beneficiario` (`idBeneficiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Falta_Motivo1`
    FOREIGN KEY (`motivo_idMotivo`)
    REFERENCES `REDO_MAKMA`.`Motivo` (`idMotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`FaltaOtro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`FaltaOtro` (
  `idFaltaOtro` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(50) NOT NULL,
  `falta_idFalta` INT NOT NULL,
  PRIMARY KEY (`idFaltaOtro`),
  INDEX `fk_FaltaOtro_Falta1_idx` (`falta_idFalta` ASC),
  CONSTRAINT `fk_FaltaOtro_Falta1`
    FOREIGN KEY (`falta_idFalta`)
    REFERENCES `REDO_MAKMA`.`Falta` (`idFalta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REDO_MAKMA`.`JustificacionOtro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REDO_MAKMA`.`JustificacionOtro` (
  `idJustificacionOtro` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(50) NOT NULL,
  `justificacion_idJustificacion` INT NOT NULL,
  PRIMARY KEY (`idJustificacionOtro`),
  INDEX `fk_JustificacionOtro_Justificacion1_idx` (`justificacion_idJustificacion` ASC),
  CONSTRAINT `fk_JustificacionOtro_Justificacion1`
    FOREIGN KEY (`justificacion_idJustificacion`)
    REFERENCES `REDO_MAKMA`.`Justificacion` (`idJustificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
